# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

# EXT POWER
CONFIG_ZMK_EXT_POWER=y

CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y