# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

# EXT POWER
CONFIG_ZMK_EXT_POWER=y

# EC11 encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ZMK Studio (центральная сторона)
CONFIG_ZMK_STUDIO=y

# Split настройки центральной стороны
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
