#
# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
#
# go to sleep after one hour (1*60*60*1000ms)

CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

CONFIG_ZMK_SLEEP=y





CONFIG_WS2812_STRIP=y
CONFIG_LED_STRIP=y
CONFIG_SPI=y

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

# Keep normal RGB control available, but do not rely on RGB_OFF for LED blink power.
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_BATTERY_REPORTING=y

# Uncomment the following line to enable NKRO
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Some operating systems have problems with full support for consumer keycodes.
# Uncomment the following line if keycodes labeled "consumer" like C_AC_SEARCH don't work
#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Mouse enable
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BACKLIGHT=y
CONFIG_ZMK_BACKLIGHT_BRT_START=100
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8


# ===============================
# Patched WS2812 widget
# ===============================
CONFIG_WS2812_WIDGET=y

CONFIG_WS2812_WIDGET_USE_EXT_POWER=y
CONFIG_WS2812_WIDGET_EXT_POWER_STARTUP_DELAY_MS=80
CONFIG_WS2812_WIDGET_RESTORE_EXT_POWER_OFF=y

CONFIG_WS2812_WIDGET_SHOW_LAYER_CHANGE=y
CONFIG_WS2812_WIDGET_SHOW_LAYER_COLORS=n

CONFIG_WS2812_WIDGET_LAYER_TRIGGER_0=7
CONFIG_WS2812_WIDGET_LAYER_TRIGGER_1=11
CONFIG_WS2812_WIDGET_LAYER_TRIGGER_2=255

CONFIG_WS2812_WIDGET_LAYER_COLOR_ON=0xFFFFFF
CONFIG_WS2812_WIDGET_LAYER_COLOR_OFF=0xFF0000
CONFIG_WS2812_WIDGET_LAYER_COLOR_MANUAL=0xFFFFFF

# Layer blink: one long blink, 1 second.
CONFIG_WS2812_WIDGET_LAYER_BLINK_MS=1000
CONFIG_WS2812_WIDGET_LAYER_BLINK_REPEAT=1
CONFIG_WS2812_WIDGET_LAYER_BLINK_PAUSE_MS=1000
CONFIG_WS2812_WIDGET_LAYER_DEBOUNCE_MS=30

# Battery test threshold: 90%.
# Later change this to 20.
CONFIG_WS2812_WIDGET_SHOW_BATTERY=y
CONFIG_WS2812_WIDGET_BATTERY_LEVEL_CRITICAL=90
CONFIG_WS2812_WIDGET_BATTERY_COLOR_CRITICAL=0xFF0000

# Battery blink: short blink, 1 second pause, 3 times.
CONFIG_WS2812_WIDGET_BATTERY_BLINK_MS=180
CONFIG_WS2812_WIDGET_BATTERY_BLINK_REPEAT=3
CONFIG_WS2812_WIDGET_BATTERY_BLINK_PAUSE_MS=1000
CONFIG_WS2812_WIDGET_BATTERY_PERIODIC_MS=60000

CONFIG_WS2812_WIDGET_INTERVAL_MS=180

CONFIG_WS2812_WIDGET_SHOW_CONNECTIVITY=n
