manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: myzmk
      url-base: https://github.com/ТВОЙ_АККАУНТ

  projects:
    - name: eyelash_corne
      url: https://github.com/a741725193/zmk-new_corne
      revision: main

    - name: zmk
      remote: myzmk
      revision: ws2812-overlay-v0.3.0
      import: app/west.yml

  self:
    path: config
